23WebAPIAssignment/Controllers/PoDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace _23WebAPIAssignment.Controllers
{
    public class PoDetailController : Controller
    {
        // GET: PoDetail
        public ActionResult Index()
        {
            List<PODETAIL> model = new List<PODETAIL>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:31766/api/");

                //HTTP GET
                var getTask = client.GetAsync("PODetailAPI");
                getTask.Wait();

                var result = getTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    model = result.Content.ReadAsAsync<List<PODETAIL>>().Result;
                }
            }
            return View(model);
        }

        public ActionResult Details(string id)
        {
            PODETAIL model = new PODETAIL();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:31766/api/");

                //HTTP GET
                var getTask = client.GetAsync("PODetailAPI/" + id);
                getTask.Wait();

                var result = getTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    model = result.Content.ReadAsAsync<PODETAIL>().Result;
                }
            }
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(PODETAIL collection)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:31766/api/");

                    //HTTP POST
                    var postTask = client.PostAsJsonAsync<PODETAIL>("PODetailAPI", collection);
                    postTask.Wait();

                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            PODETAIL model = new PODETAIL();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:31766/api/");

                //HTTP GET
                var getTask = client.GetAsync("PODetailAPI/" + id);
                getTask.Wait();

                var result = getTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    model = result.Content.ReadAsAsync<PODETAIL>().Result;
                }
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(PODETAIL collection)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:31766/api/");

                    //HTTP POST
                    var postTask = client.PutAsJsonAsync<PODETAIL>("PODetailAPI/" + collection.PONO, collection);
                    postTask.Wait();

                    var result = postTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:31766/api/");

                //HTTP POST
                var postTask = client.DeleteAsync("PODetailAPI/" + id);
                postTask.Wait();

                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index");
        }


    }
}

23WebAPIAssignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("23 WEB API Assignment", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Supplier", "Index", "Supplier", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Item", "Index", "Item", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("POMaster", "Index", "POMaster", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("PODetail", "Index", "PoDetail", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 23 Web API Assignment</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>